name: Deploy React Playground to GitHub Pages

on:
  push:
    branches:
      - main  # deploy on pushes to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build the Vite project
      - name: Build project
        run: npm run build

      # 5. Deploy to GitHub Pages (first-time safe)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./dist
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          allow_empty_commit: true   # helps first-time deploy if branch doesn't exist
          keep_files: false           # ensures only latest build files are deployed
          enable_jekyll: false        # prevents GitHub from ignoring files
